<a href="https://colab.research.google.com/github/Zakariya-02/Introduction-to-AI-2026/blob/main/NumPyClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
numbers = np.array ([1, 2, 3 , 4, 5])

In [ ]:
print(numbers)
[1, 2, 3, 4, 5]

[1 2 3 4 5]


[1, 2, 3, 4, 5]

In [ ]:
marks = [56, 67, 90, 76, 80]
print(marks)
[56, 67, 90, 76, 80]

[56, 67, 90, 76, 80]


[56, 67, 90, 76, 80]

**List versus Arrays**

In [ ]:
cat1 = [23, 45, 24, 50]
cat2 = [45, 50, 30, 39]
print(cat1)
print(cat2)
print(cat1+cat2)

[23, 45, 24, 50]
[45, 50, 30, 39]
[23, 45, 24, 50, 45, 50, 30, 39]


**Create Arrays with functions **

In [ ]:
zeros = np.zeros(15)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
numbers = np.arange(1, 11)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


**using intervals**

In [ ]:
even_numbers = np.arange(2, 21, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
odd_numbers = np.arange(1, 21, 2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19]


**Array indexing**

In [ ]:
students = np.array(["Irena", "Irfan", "Moksh", "Rudra", "Vinicius", "Mbappe"])
print(students[0])
print(students[-1])

Irena
Mbappe


**Array slicing: slicing means choosing multiple elements**

In [ ]:
print(students[1:4])
print(students[:3]) # prints first 3 elements
print(students[-2:]) # prints last 2 elements
print(students[::2]) # skips values

['Irfan' 'Moksh' 'Rudra']
['Irena' 'Irfan' 'Moksh']
['Vinicius' 'Mbappe']
['Irena' 'Moksh' 'Vinicius']


marks(14, 34, 56, 89, 45, 35, 67, 56,54,43) create an array called marks, and print the first mark, the last mark, print marks from index 2 to 4, and print every second value.

In [ ]:
Marks = np.array (["14", "34","89", "45", "35", "67", "56","54","43"])
print(Marks[0])
print(marks[-1])
print(marks[::2])
print(marks[2:4])



14
80
[56, 90, 80]
[90, 76]


**two dimensional arrays**

In [ ]:
matrix = np.array([
    [1, 2, 3, 0]
    [4, 5, 6, 0]
    [7, 8, 9 , 0]
])
print(matrix.shape)
print(matrix)

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_1550/1694255063.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1, 2, 3, 0]


TypeError: list indices must be integers or slices, not tuple

**Mathematical operations**

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([7, 8, 13, 14, 5])
print(array1 + array2) #addition
print(array1 - array2) #subtraction
print(array1 * array2) #multiplaction
print(array1 / array2) #Division
print(array1*2) #multiplying by a number

[ 8 10 16 18 10]
[ -6  -6 -10 -10   0]
[ 7 16 39 56 25]
[0.14285714 0.25       0.23076923 0.28571429 1.        ]
[ 2  4  6  8 10]


**A student has the following marks that were entered out of 40. conver them to percantages: 34, 27, 35, 20, 60**

**Exercise 3:** Create a 3*4 array representing 3 students and 4 subjects. then, find the total marks per student, average marks per student and highest score in the class

In [10]:
import numpy as np


marks = np.array([
    [78, 85, 90, 88],   # Student 1
    [65, 70, 75, 80],   # Student 2
    [92, 89, 95, 91]    # Student 3
])


total_marks = np.sum(marks, axis=1)


average_marks = np.mean(marks, axis=1)


highest_score = np.max(marks)


print("Marks Array:")
print(marks)

print("\nTotal Marks per Student:", total_marks)
print("Average Marks per Student:", average_marks)
print("Highest Score in the Class:", highest_score)

Marks Array:
[[78 85 90 88]
 [65 70 75 80]
 [92 89 95 91]]

Total Marks per Student: [341 290 367]
Average Marks per Student: [85.25 72.5  91.75]
Highest Score in the Class: 95
